# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  run-test:
    desc: Runs test script that fetches the actual data from GitLab API
    cmds:
      - ./scripts/test_local.sh
  
  run-unit-tests:
    desc: Run test suite
    cmds:
      - uv run python3 -m pytest -vvs tests/unit

  run-linters:
    desc: Run linters and type checker
    cmds:
      - uv run ruff check --fix && uv run ruff format && uv run ty check
    dotenv: ['.env.test']

  run-engine:
    desc: Run AI Code Review Engine
    cmds:
      - uv run main.py
    dotenv: ['.env']
  
  run-indexer:
    desc: Run repo indexer
    cmds:
      - echo "Run indexer"
    dotenv: ['.env']

  build-image:
    desc: Build the Docker image locally (tagged as themis:dev)
    cmds:
      - docker build -t themis:dev .
